In [4]:
import numpy as np

In [7]:
#create a array size of 10, filled with zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# array starting from 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
# matrix 2x2, filled with ones
np.ones([2,2], dtype = int)

array([[1, 1],
       [1, 1]])

In [24]:
#Create a numpy matrix of 3*2 float numbers, filled with ones
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
#Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones

X = np.arange(10,20,2)
print(X)
np.ones_like(X)

[10 12 14 16 18]


array([1, 1, 1, 1, 1])

In [57]:
#Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

X = np.array([[1,2,3],[1,2,3]])
print(X)
np.zeros_like(X)

[[1 2 3]
 [1 2 3]]


array([[0, 0, 0],
       [0, 0, 0]])

In [83]:
# Create a numpy matrix of 4*4 integers, filled with fives.¶

x = np.ones([4,4], dtype= int)
print(x)
x*5

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [92]:
#Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
X = np.array([[2,3], [6,2]])
#print(X)
Y = np.ones_like(X)*7
print(Y)

[[7 7]
 [7 7]]


In [19]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.¶
#np.array([[0,1,1],[1,1,0]])
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
 #Create a numpy array, filled with 3 random integer values between 1 and 10
np.random.randint(10,size =3) 

array([9, 3, 2])

In [ ]:
# Given the X python list convert it to an Y numpy array¶
X = [1,2,3,4]
print(type(X))
Y = np.array(X)
print(Y)

In [21]:
a = np.arange(5)
a+20
print(a)



[0 1 2 3 4]


In [70]:

X = np.array([33,55,33,5,56])

mask = (X == 33) | (X ==5)


X[mask]

array([33, 33,  5])

In [77]:
X = np.array([33,55,33,5,56])
X.mean()
#mask = X> X.mean()

#X[mask]

array([55, 56])

In [5]:
np.random.random(size=3)


array([0.38330954, 0.78578042, 0.33010755])

In [12]:
np.random.normal(size=3)

array([1.18641106, 0.95358444, 0.4281912 ])

In [15]:
np.random.rand(2, 4)


array([[0.69178917, 0.6205326 , 0.02205505, 0.26850535],
       [0.17833464, 0.41277085, 0.76267995, 0.21781965]])

In [16]:
np.arange(10).reshape(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [6]:
3 + None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [8]:
a = np.array([1, 2, 3, np.nan, None, 4], dtype='float')
print(a)


[ 1.  2.  3. nan nan  4.]


In [11]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])


nan


In [12]:
3+ np.inf

inf

In [13]:
np.isnan(np.nan)


True

In [19]:
np.isinf(np.inf)


True

In [15]:
np.isfinite(np.nan), np.isfinite(np.inf)


(False, False)

In [20]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))


array([False, False, False,  True, False, False])

In [21]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))


array([False, False, False, False,  True, False])

In [22]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))


array([ True,  True,  True, False, False,  True])

In [27]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])


In [25]:
a[~np.isnan(a)]


array([1., 2., 3., 4.])

In [30]:
a[np.isfinite(a)]


array([1., 2., 3., 4.])

In [31]:
a[np.isfinite(a)].sum()


10.0

In [ ]:
a[np.isfinite(a)].mean()


In [35]:
pd.Series([1, 2,5, np.nan]).count()


3

In [40]:
pd.Series([9, np.nan,9]).sum()


18.0

In [41]:
pd.Series([2, 2, np.nan]).mean()


2.0

In [42]:
s = pd.Series([1, 2, 3, np.nan, np.nan, 4])


In [44]:
s[s.notnull()]

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [45]:
s.dropna()

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [46]:
df = pd.DataFrame({
    'Column A': [1, np.nan, 30, np.nan],
    'Column B': [2, 8, 31, np.nan],
    'Column C': [np.nan, 9, 32, 100],
    'Column D': [5, 8, 34, 110],
})

In [47]:
df

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [50]:
df.shape

(4, 4)

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Column A  2 non-null      float64
 1   Column B  3 non-null      float64
 2   Column C  3 non-null      float64
 3   Column D  4 non-null      int64  
dtypes: float64(3), int64(1)
memory usage: 256.0 bytes


In [52]:
df.describe()

Column A   Column B    Column C    Column D
count   2.000000   3.000000    3.000000    4.000000
mean   15.500000  13.666667   47.000000   39.250000
std    20.506097  15.307950   47.318073   48.931074
min     1.000000   2.000000    9.000000    5.000000
25%     8.250000   5.000000   20.500000    7.250000
50%    15.500000   8.000000   32.000000   21.000000
75%    22.750000  19.500000   66.000000   53.000000
max    30.000000  31.000000  100.000000  110.000000

In [61]:
df.dropna(axis=0)

Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [62]:
df.dropna(axis=1)

Column D
0         5
1         8
2        34
3       110

In [63]:
df.isnull()

Column A  Column B  Column C  Column D
0     False     False      True     False
1      True     False     False     False
2     False     False     False     False
3      True      True     False     False

In [64]:
df.isnull().sum()

Column A    2
Column B    1
Column C    1
Column D    0
dtype: int64

In [65]:
df.dropna(axis=1)


Column D
0         5
1         8
2        34
3       110

In [69]:
df2 = pd.DataFrame({
    'Column A': [1, np.nan, 30,],
    'Column B': [2, np.nan, 31],
    'Column C': [np.nan, np.nan, 100]
})

In [67]:
df2

Column A  Column B  Column C
0       1.0       2.0       NaN
1       NaN       NaN       NaN
2      30.0      31.0     100.0

In [70]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Column A  2 non-null      float64
 1   Column B  2 non-null      float64
 2   Column C  1 non-null      float64
dtypes: float64(3)
memory usage: 200.0 bytes


In [76]:
df2.dropna(how='any')

Column A  Column B  Column C
2      30.0      31.0     100.0

In [89]:
df.dropna(thresh=2)


Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [93]:
df.fillna(df.mean())

Column A   Column B  Column C  Column D
0       1.0   2.000000      47.0         5
1      15.5   8.000000       9.0         8
2      30.0  31.000000      32.0        34
3      15.5  13.666667     100.0       110

In [94]:
df

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [1]:
import numpy as np
import pandas as pd


In [4]:
pd.isnull(None)

True

In [5]:
pd.notnull(None)

False

In [6]:
pd.notnull('Hello')

True

In [9]:
pd.notnull(pd.Series([1,3,np.nan]))

0     True
1     True
2    False
dtype: bool

In [33]:
b= pd.isnull(pd.DataFrame({
    'Column A': [1, np.nan, 7],
    'Column B': [np.nan, 2, 3],
    'Column C': [np.nan, 2, np.nan]
}))

In [35]:
b.describe()

Column A Column B Column C
count         3        3        3
unique        2        2        2
top       False    False     True
freq          2        2        2

In [15]:
pd.Series([1,2,3]).count()

3

In [16]:
pd.Series([1,2,3,4]).sum()

10

In [27]:
a= pd.Series([1,2,3,np.nan, None])
print(a)

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
dtype: float64


In [30]:
a+3

0    4.0
1    5.0
2    6.0
3    NaN
4    NaN
dtype: float64

In [24]:
a.sum()

3

In [28]:
a.count()

3

In [29]:
a.mean()

2.0

In [36]:
a

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
dtype: float64

In [37]:
a.dropna()

0    1.0
1    2.0
2    3.0
dtype: float64

In [82]:
df = pd.DataFrame({
    'Column A': [1, np.nan, 30, np.nan],
    'Column B': [2, 8, 31, np.nan],
    'Column C': [np.nan, 9, 32, 3],
    'Column D': [5, 8, 34, 3],
})

In [40]:
df.describe()

Column A   Column B    Column C    Column D
count   2.000000   3.000000    3.000000    4.000000
mean   15.500000  13.666667   47.000000   39.250000
std    20.506097  15.307950   47.318073   48.931074
min     1.000000   2.000000    9.000000    5.000000
25%     8.250000   5.000000   20.500000    7.250000
50%    15.500000   8.000000   32.000000   21.000000
75%    22.750000  19.500000   66.000000   53.000000
max    30.000000  31.000000  100.000000  110.000000

In [75]:
df

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN       5.0
1       NaN       8.0       9.0       8.0
2      30.0      31.0      32.0      34.0
3       NaN       NaN       NaN       NaN

In [74]:
df.isnull().sum()

Column A    2
Column B    1
Column C    2
Column D    1
dtype: int64

In [79]:
df.notnull()

Column A  Column B  Column C  Column D
0      True      True     False      True
1     False      True      True      True
2      True      True      True      True
3     False     False     False     False

In [77]:
df.count()

Column A    2
Column B    3
Column C    2
Column D    3
dtype: int64

In [80]:
df.dropna()

Column A  Column B  Column C  Column D
2      30.0      31.0      32.0      34.0

In [83]:
df.dropna(axis=1)

Column D
0         5
1         8
2        34
3         3

In [95]:
df2 = pd.DataFrame({
    'Column A': [1, np.nan, 30],
    'Column B': [2, np.nan, 31],
    'Column C': [np.nan, np.nan, 100],
})

In [97]:
df2

Column A  Column B  Column C
0       1.0       2.0       NaN
1       NaN       NaN       NaN
2      30.0      31.0     100.0

In [99]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Column A  2 non-null      float64
 1   Column B  2 non-null      float64
 2   Column C  1 non-null      float64
dtypes: float64(3)
memory usage: 200.0 bytes


In [104]:
df2.dropna(how='any')

Column A  Column B  Column C
2      30.0      31.0     100.0

In [105]:
df2.fillna(2)

Column A  Column B  Column C
0       1.0       2.0       2.0
1       2.0       2.0       2.0
2      30.0      31.0     100.0

In [108]:
df2.dropna(thresh=1,axis = 1)

Column A  Column B  Column C
0       1.0       2.0       NaN
1       NaN       NaN       NaN
2      30.0      31.0     100.0

In [109]:
df2.dropna(thresh = 1, axis = 0)

Column A  Column B  Column C
0       1.0       2.0       NaN
2      30.0      31.0     100.0

In [124]:
df2.fillna(2,axis=0)

Column A  Column B  Column C
0       1.0       2.0       2.0
1       2.0       2.0       2.0
2      30.0      31.0     100.0

In [126]:
s = pd.Series([1,3,None,4,6,np.nan])

In [130]:
s.dropna().count()

4

In [135]:
len(s)

6

In [133]:
s.count()

4

In [137]:
s.notnull()


0     True
1     True
2    False
3     True
4     True
5    False
dtype: bool

In [138]:
pd.Series([1, np.nan]).isnull().any()


True

In [139]:
pd.Series([1, 2]).isnull().any()



False

In [140]:
s.isnull().any()


True

In [142]:
s.notnull().values


array([ True,  True, False,  True,  True, False])

In [143]:
s.notnull().values.any()


True